#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -r processor*

decomposePar

rm log.*

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication blockMesh
#runApplication setFields
#runApplication $(getApplication)

runParallel $(getApplication)

#------------------------------------------------------------------------------
